### ISSUE TITLE
List ZNC version you use

### ISSUE THREAD

**Issue by sindresorhus** [ircrelay/suggestions#5]
Would be useful to know which version of ZNC you use. You actually don't even list that you use ZNC, but I inferred it from another issue. It's useful to know what features I can use.

I want to add in server-time in my client, but the option changes between ZNC 1.0 and the master: 

http://dev.weechat.org/post/2012/11/27/Tags-in-IRC-messages

> Note: with znc 1.0, the server capability was "znc.in/server-time". With znc git > 1.0, the capability is "znc.in/server-time-iso".

**Comment by mitchellh** [comment]
Hi Sindre!

It would probably actually be more helpful to list the features we support, rather than the ZNC version. We run ZNC 0.206, but it is _heavily_ modified. We backported a lot of security patches, and we run over 15 custom C++ modules. One of these modules we wrote actually adds support for server-time into ZNC 0.206.

Therefore, perhaps we should just list the features we use. We'll think about that.

In the meantime, you can enable server-time in your client, and it will work fine!

Best,
Mitchell

**Comment by sindresorhus** [comment]
Any plans to upgrade to ZNC 1.0?

**Comment by mitchellh** [comment]
Not in the short term. If there are security issues we'll backport them if possible. Otherwise, probably only if there is a compelling feature reason.
